<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PlaceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('places')->insert([
            [
                'name' => 'Quán Cơm Tấm Hoa Mai',
                'description' => 'Cơm tấm nướng ngon, giá rẻ, luôn khách đông đúc',
                'category_id' => 1,
                'address' => '123 Đường Tương Tư, TP. Vĩnh Long',
                'latitude' => 10.2672,
                'longitude' => 106.1674,
                'phone' => '0276-3826001',
                'email' => 'hoamai@comdai.vn',
                'website' => 'https://comdai.vn',
                'image' => 'https://via.placeholder.com/300x200?text=Cơm+Tấm+Hoa+Mai',
                'rating' => 4.5,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Phở Bò Thảo Nguyên',
                'description' => 'Phở bò ngon, nước dùng thơm, nồi lửa vừa phải',
                'category_id' => 2,
                'address' => '456 Đường Nguyễn Huệ, TP. Vĩnh Long',
                'latitude' => 10.2700,
                'longitude' => 106.1700,
                'phone' => '0276-3826002',
                'email' => 'pho@thaonguyen.vn',
                'website' => 'https://pho.vn',
                'image' => 'https://via.placeholder.com/300x200?text=Phở+Bò',
                'rating' => 4.3,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nhà Hàng Hải Sản Golden',
                'description' => 'Hải sản tươi sống, chế biến tài tình, không gian sang trọng',
                'category_id' => 3,
                'address' => '789 Đường Cách Mạng Tháng 8, TP. Vĩnh Long',
                'latitude' => 10.2680,
                'longitude' => 106.1690,
                'phone' => '0276-3826003',
                'email' => 'golden@haisan.vn',
                'website' => 'https://haisan.vn',
                'image' => 'https://via.placeholder.com/300x200?text=Hải+Sản',
                'rating' => 4.7,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Cà Phê Vĩnh Long',
                'description' => 'Cà phê chuyên nghiệp, không gian yên tĩnh, wifi miễn phí',
                'category_id' => 4,
                'address' => '321 Đường Tại Tương Tư, TP. Vĩnh Long',
                'latitude' => 10.2685,
                'longitude' => 106.1680,
                'phone' => '0276-3826004',
                'email' => 'cafe@vinhlong.vn',
                'website' => 'https://cafe-vl.vn',
                'image' => 'https://via.placeholder.com/300x200?text=Cà+Phê',
                'rating' => 4.2,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bún Riêu Cua Thơm',
                'description' => 'Bún riêu cua cà chua tuyệt vời, nước dùng đậm đà',
                'category_id' => 2,
                'address' => '654 Đường Nguyễn Biểu, TP. Vĩnh Long',
                'latitude' => 10.2620,
                'longitude' => 106.1720,
                'phone' => '0276-3826005',
                'email' => 'bunrieu@thom.vn',
                'website' => 'https://bunrieu.vn',
                'image' => 'https://via.placeholder.com/300x200?text=Bún+Riêu',
                'rating' => 4.5,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Cơm Gà Hải Nam Ngon',
                'description' => 'Cơm gà hải nam gà tươi, cơm thơm nước mũi',
                'category_id' => 1,
                'address' => '987 Đường Võ Văn Kiệt, TP. Vĩnh Long',
                'latitude' => 10.2500,
                'longitude' => 106.1680,
                'phone' => '0276-3826006',
                'email' => 'comga@hainam.vn',
                'website' => 'https://comga.vn',
                'image' => 'https://via.placeholder.com/300x200?text=Cơm+Gà',
                'rating' => 4.6,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bánh Mì Nóng Hương Ngon',
                'description' => 'Bánh mì nóng với pâté, chả cua, rau sạch tươi',
                'category_id' => 1,
                'address' => '234 Đường Đinh Bộ Lĩnh, TP. Vĩnh Long',
                'latitude' => 10.2430,
                'longitude' => 106.1620,
                'phone' => '0276-3826007',
                'email' => 'banh@mi.vn',
                'website' => 'https://banh-mi.vn',
                'image' => 'https://via.placeholder.com/300x200?text=Bánh+Mì',
                'rating' => 4.3,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Cá Lóc Nướng Mắm',
                'description' => 'Cá lóc nướng mắm dừa, cơm tấm sườn nướng',
                'category_id' => 3,
                'address' => '567 Đường Phan Bội Châu, TP. Vĩnh Long',
                'latitude' => 10.2550,
                'longitude' => 106.1740,
                'phone' => '0276-3826008',
                'email' => 'ca@loc.vn',
                'website' => 'https://ca-loc.vn',
                'image' => 'https://via.placeholder.com/300x200?text=Cá+Lóc',
                'rating' => 4.7,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bún Hải Sản Song Thủy',
                'description' => 'Bún hải sản tươi sống với tôm, cua, mực ngon lành',
                'category_id' => 2,
                'address' => '111 Đường Lý Thái Tổ, TP. Vĩnh Long',
                'latitude' => 10.2600,
                'longitude' => 106.1650,
                'phone' => '0276-3826009',
                'email' => 'bun@haisan.vn',
                'website' => 'https://bun-haisan.vn',
                'image' => 'https://via.placeholder.com/300x200?text=Bún+Hải+Sản',
                'rating' => 4.4,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Chè Ba Màu Nguyên Lê',
                'description' => 'Chè ba màu lạnh, dừa mệm, đậu đỏ bùi bùi',
                'category_id' => 4,
                'address' => '888 Đường 30/4, TP. Vĩnh Long',
                'latitude' => 10.2580,
                'longitude' => 106.1700,
                'phone' => '0276-3826010',
                'email' => 'che@bamauu.vn',
                'website' => 'https://che-ba-mau.vn',
                'image' => 'https://via.placeholder.com/300x200?text=Chè+Ba+Màu',
                'rating' => 4.2,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
